import { KanbanData } from "../types/KanbanTypes";

export const KANBAN_DATA: KanbanData = {
  designChallenge: {
    columns: [
      {
        id: "customer",
        title: "Customer",
        icon: "/assets/icons/customer.png",
        items: [
          {
            id: "dc1",
            title: "Start Engagement",
            icon: "/assets/icons/customer.png",
            tooltip:
              "NASA initiated the project with Topcoder to redesign its drone control interface for safety and usability.",
            connectedTo: "do1",
            position: "start",
            verticalPosition: 0,
          },
          {
            id: "dc2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/customer.png",
            tooltip:
              "NASA worked closely with Topcoder to define user needs, interface goals, and required features.",
            connectedTo: ["dd2"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
          },
          {
            id: "dc3",
            title: "Review Round 1 Designs",
            icon: "/assets/icons/customer.png",
            tooltip:
              "NASA reviewed the initial design submissions and provided detailed feedback to guide refinement.",
            verticalPosition: 2,
            connectedTo: ["rev1", "do5"],
            position: "both",
          },
          {
            id: "dc4",
            title: "Final Review and Select Winners",
            icon: "/assets/icons/customer.png",
            tooltip:
              "NASA conducted a final review of all submissions and selected the best designs based on usability, alignment with requirements, and visual quality.",
            verticalPosition: 3,
            connectedTo: "rev2",
            position: "end",
          },
        ],
      },
      {
        id: "delivery",
        title: "Topcoder Delivery",
        icon: "/assets/icons/topcoder.png",
        items: [
          {
            id: "dd1",
            title: "Requirement and Feasible Study",
            icon: "/assets/icons/topcoder.png",
            tooltip:
              "Topcoder analyzed NASA’s requirements and confirmed that the redesign was feasible with available tools and timelines.",
            connectedTo: "do1",
            position: "end",
            isVerticalConnection: true,
            verticalPosition: 0,
          },
          {
            id: "dd2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/topcoder.png",
            tooltip:
              "A Topcoder copilot and project manager worked with NASA to turn initial ideas into actionable design tasks and clear design goals.",
            connectedTo: ["dc2", "do2", "dd3"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
            verticalConnectionTarget: "dd3",
          },
          {
            id: "dd3",
            title: "Design Challenge",
            icon: "/assets/icons/topcoder.png",
            tooltip:
              "A design challenge was launched to crowdsource interface ideas for NASA’s control station.",
            verticalPosition: 2,
            connectedTo: ["do3", "dd2"],
            position: "both",
            isVerticalConnection: true,
          },
          {
            id: "dd4",
            title: "Documentation & forum",
            icon: "/assets/icons/topcoder.png",
            tooltip:
              "Provided design briefs, references, and support to help designers align with NASA's vision.",
            verticalPosition: 3,
            connectedTo: "com3",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "operation",
        title: "Platform",
        icon: "/assets/icons/platform.svg",
        items: [
          {
            id: "do1",
            title: "Team Allocation",
            icon: "/assets/icons/teamAllocation.svg",
            tooltip:
              "Topcoder assigned a copilot and project manager to manage challenge delivery and quality.",
            connectedTo: ["dc1", "dd1"],
            position: "both",
            verticalConnectionTarget: "dd1",
            verticalPosition: 0,
          },
          {
            id: "do2",
            title: "Write Specification",
            icon: "/assets/icons/specification.svg",
            tooltip:
              "Detailed specs were written for layout, components, interactions, and design constraints.",
            connectedTo: "dd2",
            position: "end",
            verticalPosition: 1,
          },
          {
            id: "do3",
            title: "Challenge Posting",
            icon: "/assets/icons/challengePosting.png",
            tooltip:
              "The design challenge was published on the Topcoder platform for the global design community.",
            verticalPosition: 2,
            connectedTo: ["dd3", "do4"],
            position: "both",
            verticalConnectionTarget: "do4",
          },
          {
            id: "do4",
            title: "Notification",
            icon: "/assets/icons/notification.svg",
            tooltip:
              "The Topcoder community was notified via emails, platform alerts, and social media posts.",
            verticalPosition: 3,
            connectedTo: ["do3", "com1"],
            position: "both",
            isVerticalConnection: true,
          },
          {
            id: "do5",
            title: "Announce Round 1 Feedback",
            icon: "/assets/icons/AnounceRounde1.svg",
            tooltip: "",
            verticalPosition: 4,
            connectedTo: "rev1",
            position: "end",
          },
          {
            id: "do6",
            title: "Announce Winners",
            icon: "/assets/icons/Anouncewinner.svg",
            tooltip:
              "Winning designs were announced to the community and finalists.",
            verticalPosition: 5,
            connectedTo: "dc4",
            position: "end",
          },
          {
            id: "do7",
            title: "Prepare Deliverables",
            icon: "/assets/icons/prepareDeliverable.svg",
            tooltip: "Prepare and package final design deliverables",
            verticalPosition: 6,
            connectedTo: "do6",
            position: "end",
          },
        ],
      },
      {
        id: "community",
        title: "Community",
        icon: "/assets/icons/community.svg",
        items: [
          {
            id: "com1",
            title: "Join Challenge",
            icon: "/assets/icons/community.svg",
            tooltip: "Community members join the challenge",
            verticalPosition: 0,
            connectedTo: "do4",
            position: "end",
          },
          {
            id: "com2",
            title: "Ask question",
            icon: "/assets/icons/askquestion.svg",
            tooltip: "Community members can ask questions about the challenge",
            verticalPosition: 1,
            connectedTo: ["com1", "com3"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "com3",
          },
          {
            id: "com3",
            title: "Documentation & forum",
            icon: "/assets/icons/documentationAndForum.svg",
            tooltip:
              "Access documentation and participate in forum discussions",
            verticalPosition: 2,
            connectedTo: ["com2", "dd4", "com4"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "com4",
          },
          {
            id: "com4",
            title: "Submit Round 1 Designs",
            icon: "/assets/icons/submitRound1Design.svg",
            tooltip: "Community members submit their initial design proposals",
            verticalPosition: 3,
            connectedTo: ["com3", "rev1"],
            position: "both",
            isVerticalConnection: true,
          },
          {
            id: "com5",
            title: "Submit Round 2 Designs",
            icon: "/assets/icons/submitRound1Design.svg",
            tooltip: "Community members submit their revised design proposals",
            verticalPosition: 4,
            connectedTo: "do5",
            position: "end",
          },
        ],
      },
      {
        id: "review",
        title: "Review Panel",
        icon: "/assets/icons/review.svg",
        items: [
          {
            id: "rev1",
            title: "Review Round 1 Designs",
            icon: "/assets/icons/reviewRound.svg",
            tooltip: "Review panel evaluates initial design submissions",
            verticalPosition: 0,
            connectedTo: ["com4", "dc3"],
            position: "both",
          },
          {
            id: "rev2",
            title: "Review Round 2 Designs",
            icon: "/assets/icons/reviewRound.svg",
            tooltip: "Review panel evaluates revised design submissions",
            verticalPosition: 1,
            connectedTo: "com5",
            position: "end",
          },
        ],
      },
    ],
    description:
      "NASA set out to redesign its drone control station with a sharper focus on usability, safety, and efficiency. Through a series of Topcoder design challenges, they explored innovative interface solutions to support real-time flight tracking, emergency handling, and multi-drone operations. Here's how the Topcoder workflows of project and challenge management led to success:",
  },
  // Add similar data structure for other challenge types
  devChallenge: {
    columns: [
      {
        id: "customer",
        title: "Customer",
        icon: "/assets/icons/devCustomer.svg",
        items: [
          {
            id: "dc1",
            title: "Start Engagement",
            icon: "/assets/icons/devCustomer.svg",
            tooltip:
              "NASA initiated the project with Topcoder to redesign its drone control interface for safety and usability.",
            connectedTo: "do1",
            position: "start",
            verticalPosition: 0,
          },
          {
            id: "dc2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/devCustomer.svg",
            tooltip: "Customer collaborates on project requirements",
            connectedTo: ["dd2"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
          },
          {
            id: "reviewaccept",
            title: "Final Review & Acceptance",
            icon: "/assets/icons/devCustomer.svg",
            tooltip: "Review panel evaluates final submissions",
            verticalPosition: 6,
            connectedTo: "reviewAccept",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "delivery",
        title: "Delivery Platform",
        icon: "./assets/icons/topcoder.png",
        items: [
          {
            id: "dd1",
            title: "Requirement and Feasible Study",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Analyze requirements and conduct feasibility study",
            connectedTo: "do1",
            position: "end",
            isVerticalConnection: true,
            verticalPosition: 0,
          },
          {
            id: "dd2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Topcoder team collaborates on requirements",
            connectedTo: ["dc2", "do2", "dd3"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
            verticalConnectionTarget: "dd3",
          },
          {
            id: "dd3",
            title: "Development Challenge",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage design challenge",
            verticalPosition: 2,
            connectedTo: ["do3", "dd2"],
            position: "both",
            isVerticalConnection: true,
          },
          {
            id: "dd4",
            title: "Documentation & forum",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage documentation and forum content",
            verticalPosition: 3,
            connectedTo: "com3",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "operation",
        title: "platform",
        icon: "/assets/icons/platform.svg",
        items: [
          {
            id: "do1",
            title: "Team Allocation",
            icon: "/assets/icons/teamAllocation.svg",
            tooltip: "Operations team assigns resources",
            connectedTo: ["dc1", "dd1"],
            position: "both",
            verticalConnectionTarget: "dd1",
            verticalPosition: 0,
          },
          {
            id: "do2",
            title: "Write Specification",
            icon: "/assets/icons/specification.svg",
            tooltip: "Platform team writes detailed specifications",
            connectedTo: "dd2",
            position: "end",
            verticalPosition: 1,
          },
          {
            id: "do3",
            title: "Challenge Posting",
            icon: "/assets/icons/challengePosting.png",
            tooltip: "Post the challenge on the platform",
            verticalPosition: 2,
            connectedTo: ["dd3", "do4"],
            position: "both",
            verticalConnectionTarget: "do4",
          },
          {
            id: "do4",
            title: "Notification",
            icon: "/assets/icons/notification.svg",
            tooltip: "Send notifications to relevant stakeholders",
            verticalPosition: 3,
            connectedTo: ["do3", "com1"],
            position: "both",
            isVerticalConnection: true,
          },
        ],
      },
      {
        id: "community",
        title: "Community",
        icon: "/assets/icons/community.svg",
        items: [
          {
            id: "com1",
            title: "Join Challenge",
            icon: "/assets/icons/community.svg",
            tooltip: "Community members join the challenge",
            verticalPosition: 0,
            connectedTo: "do4",
            position: "end",
          },
          {
            id: "com2",
            title: "Ask question",
            icon: "/assets/icons/askquestion.svg",
            tooltip: "Community members can ask questions about the challenge",
            verticalPosition: 1,
            connectedTo: ["com1", "com3"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "com3",
          },
          {
            id: "com3",
            title: "Documentation & forum",
            icon: "/assets/icons/documentationAndForum.svg",
            tooltip:
              "Access documentation and participate in forum discussions",
            verticalPosition: 2,
            connectedTo: ["com2", "dd4", "com4"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "com4",
          },
          {
            id: "com4",
            title: "Submit Solutions",
            icon: "/assets/icons/submitRound1Design.svg",
            tooltip: "Community members submit their initial design proposals",
            verticalPosition: 3,
            connectedTo: ["com3", "rev1"],
            position: "both",
            isVerticalConnection: true,
          },
        ],
      },
      {
        id: "review",
        title: "Review Panel",
        icon: "/assets/icons/review.svg",
        items: [
          {
            id: "revs",
            title: "Review Submission",
            icon: "/assets/icons/reviewRound.svg",
            tooltip: "Review panel evaluates initial design submissions",
            verticalPosition: 0,
            connectedTo: "com4",
            position: "end",
          },
          {
            id: "score",
            title: "Score Submission",
            icon: "/assets/icons/scoreSubmission.svg",
            tooltip: "sample",
            verticalPosition: 1,
            connectedTo: ["revs", "reviewAccept"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "reviewAccept",
          },
          {
            id: "reviewAccept",
            title: "Final Review & Acceptance",
            icon: "/assets/icons/finalReview.svg",
            tooltip: "Review panel evaluates final submissions",
            verticalPosition: 2,
            connectedTo: ["score", "dd4", "prepare"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "prepare",
          },
          {
            id: "prepare",
            title: "Prepare Whitepaper",
            icon: "/assets/icons/prepareWhitepaper.svg",
            tooltip: "Prepare whitepaper for the customer",
            verticalPosition: 3,
            connectedTo: "rev2",
            isVerticalConnection: true,
            position: "end",
          },
        ],
      },
    ],
    description:
      "T-Mobile needed a better way to track and visualize performance across their agile development teams by building metrics-based dashboards integrated with JIRA to drive efficiency and alignment. They partnered with Topcoder to crowdsource the solution and accelerate delivery. Here's how the Topcoder workflows of project and challenge management led to success:",
  },

  qaChallenge: {
    columns: [
      {
        id: "customer",
        title: "Customer",
        icon: "/assets/icons/qaCustomer.svg",
        items: [
          {
            id: "dc1",
            title: "Start Engagement",
            icon: "/assets/icons/qaCustomer.svg",
            tooltip:
              "NASA initiated the project with Topcoder to redesign its drone control interface for safety and usability.",
            connectedTo: "do1",
            position: "start",
            verticalPosition: 0,
          },
          {
            id: "dc2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/qaCustomer.svg",
            tooltip: "Customer collaborates on project requirements",
            connectedTo: ["dd2"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
          },
          {
            id: "reviewaccept",
            title: "Final Review & Acceptance",
            icon: "/assets/icons/qaCustomer.svg",
            tooltip: "Review panel evaluates final submissions",
            verticalPosition: 6,
            connectedTo: "reviewAccept",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "delivery",
        title: "Delivery Platform",
        icon: "./assets/icons/topcoder.png",
        items: [
          {
            id: "dd1",
            title: "Requirement and Feasible Study",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Analyze requirements and conduct feasibility study",
            connectedTo: "do1",
            position: "end",
            isVerticalConnection: true,
            verticalPosition: 0,
          },
          {
            id: "dd2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Topcoder team collaborates on requirements",
            connectedTo: ["dc2", "do2", "dd3"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
            verticalConnectionTarget: "dd3",
          },
          {
            id: "dd3",
            title: "QA Challenge",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage design challenge",
            verticalPosition: 2,
            connectedTo: ["do3", "dd2"],
            position: "both",
            isVerticalConnection: true,
          },
          {
            id: "dd4",
            title: "Documentation & forum",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage documentation and forum content",
            verticalPosition: 3,
            connectedTo: "com3",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "operation",
        title: "Platform",
        icon: "/assets/icons/platform.svg",
        items: [
          {
            id: "do1",
            title: "Team Allocation",
            icon: "/assets/icons/teamAllocation.svg",
            tooltip: "Operations team assigns resources",
            connectedTo: ["dc1", "dd1"],
            position: "both",
            verticalConnectionTarget: "dd1",
            verticalPosition: 0,
          },
          {
            id: "do2",
            title: "Write Specification",
            icon: "/assets/icons/specification.svg",
            tooltip: "Platform team writes detailed specifications",
            connectedTo: "dd2",
            position: "end",
            verticalPosition: 1,
          },
          {
            id: "do3",
            title: "Challenge Posting",
            icon: "/assets/icons/challengePosting.png",
            tooltip: "Post the challenge on the platform",
            verticalPosition: 2,
            connectedTo: ["dd3", "do4"],
            position: "both",
            verticalConnectionTarget: "do4",
          },
          {
            id: "do4",
            title: "Notification",
            icon: "/assets/icons/notification.svg",
            tooltip: "Send notifications to relevant stakeholders",
            verticalPosition: 3,
            connectedTo: ["do3", "com1"],
            position: "both",
            isVerticalConnection: true,
          },
        ],
      },
      {
        id: "community",
        title: "Community",
        icon: "/assets/icons/community.svg",
        items: [
          {
            id: "com1",
            title: "Join Challenge",
            icon: "/assets/icons/community.svg",
            tooltip: "Community members join the challenge",
            verticalPosition: 0,
            connectedTo: "do4",
            position: "end",
          },
          {
            id: "com2",
            title: "Ask question",
            icon: "/assets/icons/askquestion.svg",
            tooltip: "Community members can ask questions about the challenge",
            verticalPosition: 1,
            connectedTo: ["com1", "com3"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "com3",
          },
          {
            id: "com3",
            title: "Documentation & forum",
            icon: "/assets/icons/documentationAndForum.svg",
            tooltip:
              "Access documentation and participate in forum discussions",
            verticalPosition: 2,
            connectedTo: ["com2", "dd4", "com4"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "com4",
          },
          {
            id: "com4",
            title: "Submit Solutions",
            icon: "/assets/icons/submitRound1Design.svg",
            tooltip: "Community members submit their initial design proposals",
            verticalPosition: 3,
            connectedTo: ["com3", "rev1"],
            position: "both",
            isVerticalConnection: true,
          },
        ],
      },
      {
        id: "review",
        title: "Review Panel",
        icon: "/assets/icons/review.svg",
        items: [
          {
            id: "revs",
            title: "Review Submission",
            icon: "/assets/icons/reviewRound.svg",
            tooltip: "Review panel evaluates initial design submissions",
            verticalPosition: 0,
            connectedTo: "com4",
            position: "end",
          },
          {
            id: "score",
            title: "Score Submission",
            icon: "/assets/icons/scoreSubmission.svg",
            tooltip: "sample",
            verticalPosition: 1,
            connectedTo: ["revs", "reviewAccept"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "reviewAccept",
          },
          {
            id: "reviewAccept",
            title: "Final Review & Acceptance",
            icon: "/assets/icons/finalReview.svg",
            tooltip: "Review panel evaluates final submissions",
            verticalPosition: 2,
            connectedTo: ["score", "dd4", "prepare"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "prepare",
          },
          {
            id: "prepare",
            title: "Prepare Whitepaper",
            icon: "/assets/icons/prepareWhitepaper.svg",
            tooltip: "Prepare whitepaper for the customer",
            verticalPosition: 3,
            connectedTo: "rev2",
            isVerticalConnection: true,
            position: "end",
          },
        ],
      },
    ],
    description:
      "Microsoft Teams needed a way to match their rapid 7-day release cycle with equally fast, global QA testing. By turning to Topcoder, they unlocked the power of crowdsourced testing to scale quality assurance across geographies, devices, and OS environments. Here's how the Topcoder workflows of project and challenge management led to success:",
  },
  marathonMatch: {
    columns: [
      {
        id: "customer",
        title: "Customer",
        icon: "/assets/icons/marathonCustomer.svg",
        items: [
          {
            id: "dc1",
            title: "Start Engagement",
            icon: "/assets/icons/marathonCustomer.svg",
            tooltip:
              "NASA initiated the project with Topcoder to redesign its drone control interface for safety and usability.",
            connectedTo: "do1",
            position: "start",
            verticalPosition: 0,
          },
          {
            id: "dc2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/marathonCustomer.svg",
            tooltip: "Customer collaborates on project requirements",
            connectedTo: ["dd2"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
          },
          {
            id: "marathonreview",
            title: "Final Review & Acceptance",
            icon: "/assets/icons/marathonCustomer.svg",
            tooltip: "Review panel evaluates final submissions",
            verticalPosition: 6,
            connectedTo: "reviewAccept",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "delivery",
        title: "Delivery Platform",
        icon: "./assets/icons/topcoder.png",
        items: [
          {
            id: "dd1",
            title: "Requirement and Feasible Study",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Analyze requirements and conduct feasibility study",
            connectedTo: "do1",
            position: "end",
            isVerticalConnection: true,
            verticalPosition: 0,
          },
          {
            id: "dd2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Topcoder team collaborates on requirements",
            connectedTo: ["dc2", "do2", "DEprep"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
            verticalConnectionTarget: "dd3",
          },
          {
            id: "DEprep",
            title: "Data Engineering & Prep",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage marathon match",
            verticalPosition: 2,
            connectedTo: ["dd2", "dd4"],
            isVerticalConnection: true,
          },
          {
            id: "marathonmatch",
            title: "Marathon Match",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage documentation and forum content",
            verticalPosition: 2,
            connectedTo: ["challengeposting", "DEprep"],
            position: "both",
            isVerticalConnection: true,
          },
          {
            id: "dd4",
            title: "Documentation & forum",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage documentation and forum content",
            verticalPosition: 3,
            connectedTo: "com3",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "operation",
        title: "Platform",
        icon: "/assets/icons/platform.svg",
        items: [
          {
            id: "do1",
            title: "Team Allocation",
            icon: "/assets/icons/teamAllocation.svg",
            tooltip: "Operations team assigns resources",
            connectedTo: ["dc1", "dd1"],
            position: "both",
            verticalConnectionTarget: "dd1",
            verticalPosition: 0,
          },
          {
            id: "do2",
            title: "Write Specification",
            icon: "/assets/icons/specification.svg",
            tooltip: "Platform team writes detailed specifications",
            connectedTo: "dd2",
            position: "end",
            verticalPosition: 1,
          },
          {
            id: "challengeposting",
            title: "Challenge Posting",
            icon: "/assets/icons/challengePosting.png",
            tooltip: "Post the challenge on the platform",
            verticalPosition: 2,
            connectedTo: ["marathonmatch", "notification"],
            position: "both",
            verticalConnectionTarget: "notification",
          },
          {
            id: "notification",
            title: "Notification",
            icon: "/assets/icons/notification.svg",
            tooltip: "Send notifications to relevant stakeholders",
            verticalPosition: 3,
            connectedTo: ["challengeposting", "joinchallenge"],
            position: "both",
            isVerticalConnection: true,
          },
        ],
      },
      {
        id: "community",
        title: "Community",
        icon: "/assets/icons/community.svg",
        items: [
          {
            id: "joinchallenge",
            title: "Join Challenge",
            icon: "/assets/icons/community.svg",
            tooltip: "Community members join the challenge",
            verticalPosition: 0,
            connectedTo: "do4",
            position: "end",
          },
          {
            id: "com2",
            title: "Ask question",
            icon: "/assets/icons/askquestion.svg",
            tooltip: "Community members can ask questions about the challenge",
            verticalPosition: 1,
          },
          {
            id: "com3",
            title: "Documentation & forum",
            icon: "/assets/icons/documentationAndForum.svg",
            tooltip:
              "Access documentation and participate in forum discussions",
            verticalPosition: 2,
            connectedTo: ["com2", "dd4", "com4"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "com4",
          },
          {
            id: "com4",
            title: "Submit Solutions",
            icon: "/assets/icons/submitRound1Design.svg",
            tooltip: "Community members submit their initial design proposals",
            verticalPosition: 3,
            connectedTo: ["com3", "fedback"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "fedback",
          },
          {
            id: "fedback",
            title: "Get Feedback",
            icon: "/assets/icons/feedback.svg",
            tooltip: "Get feedback from the community",
            verticalPosition: 4,
            connectedTo: ["com4", "review"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "review",
          },
        ],
      },
      {
        id: "review",
        title: "Review Panel",
        icon: "/assets/icons/review.svg",
        items: [
          {
            id: "autoScore",
            title: "Automated System Scoring",
            icon: "/assets/icons/autoScore.svg",
            tooltip: "Automated system scoring",
          },
          {
            id: "reviewAccept",
            title: "Final Review & Acceptance",
            icon: "/assets/icons/finalReview.svg",
            tooltip: "Review panel evaluates final submissions",
            verticalPosition: 2,
            connectedTo: ["score", "dd4", "prepare"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "prepare",
          },
          {
            id: "prepare",
            title: "Prepare Whitepaper",
            icon: "/assets/icons/prepareWhitepaper.svg",
            tooltip: "Prepare whitepaper for the customer",
            verticalPosition: 3,
            connectedTo: "rev2",
            isVerticalConnection: true,
            position: "end",
          },
        ],
      },
    ],
    description:
      "Harvard Medical School faced a significant challenge: identifying tumors in medical images with greater accuracy and efficiency. They turned to Topcoder to leverage the power of crowdsourcing and innovative solutions. Here's how the Topcoder workflows of project and challenge management led to success:",
  },
  ideationChallenge: {
    columns: [
      {
        id: "customer",
        title: "Customer",
        icon: "/assets/icons/ideation.svg",
        items: [
          {
            id: "dc1",
            title: "Start Engagement",
            icon: "/assets/icons/ideation.svg",
            tooltip:
              "NASA initiated the project with Topcoder to redesign its drone control interface for safety and usability.",
            connectedTo: "do1",
            position: "start",
            verticalPosition: 0,
          },
          {
            id: "dc2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/ideation.svg",
            tooltip: "Customer collaborates on project requirements",
            connectedTo: ["dd2"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
          },
          {
            id: "reviewacceptidea",
            title: "Final Review & Acceptance",
            icon: "/assets/icons/ideation.svg",
            tooltip: "Review panel evaluates final submissions",
            verticalPosition: 6,
            connectedTo: "reviewAccept",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "delivery",
        title: "Delivery Platform",
        icon: "./assets/icons/topcoder.png",
        items: [
          {
            id: "dd1",
            title: "Requirement and Feasible Study",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Analyze requirements and conduct feasibility study",
            connectedTo: "do1",
            position: "end",
            isVerticalConnection: true,
            verticalPosition: 0,
          },
          {
            id: "dd2",
            title: "Collaborates on Requirements",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Topcoder team collaborates on requirements",
            connectedTo: ["dc2", "do2", "dd3"],
            position: "both",
            verticalPosition: 1,
            isVerticalConnection: false,
            verticalConnectionTarget: "dd3",
          },
          {
            id: "dd3",
            title: "Ideation Challenge",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage design challenge",
            verticalPosition: 2,
            connectedTo: ["do3", "dd2"],
            position: "both",
            isVerticalConnection: true,
          },
          {
            id: "dd4",
            title: "Documentation & forum",
            icon: "/assets/icons/topcoder.png",
            tooltip: "Create and manage documentation and forum content",
            verticalPosition: 3,
            connectedTo: "com3",
            position: "both",
            isBidirectional: true,
          },
        ],
      },
      {
        id: "operation",
        title: "Platform",
        icon: "/assets/icons/platform.svg",
        items: [
          {
            id: "do1",
            title: "Team Allocation",
            icon: "/assets/icons/teamAllocation.svg",
            tooltip: "Operations team assigns resources",
            connectedTo: ["dc1", "dd1"],
            position: "both",
            verticalConnectionTarget: "dd1",
            verticalPosition: 0,
          },
          {
            id: "do2",
            title: "Write Specification",
            icon: "/assets/icons/specification.svg",
            tooltip: "Platform team writes detailed specifications",
            connectedTo: "dd2",
            position: "end",
            verticalPosition: 1,
          },
          {
            id: "do3",
            title: "Challenge Posting",
            icon: "/assets/icons/challengePosting.png",
            tooltip: "Post the challenge on the platform",
            verticalPosition: 2,
            connectedTo: ["dd3", "do4"],
            position: "both",
            verticalConnectionTarget: "do4",
          },
          {
            id: "do4",
            title: "Notification",
            icon: "/assets/icons/notification.svg",
            tooltip: "Send notifications to relevant stakeholders",
            verticalPosition: 3,
            connectedTo: ["do3", "com1"],
            position: "both",
            isVerticalConnection: true,
          },
        ],
      },
      {
        id: "community",
        title: "Community",
        icon: "/assets/icons/community.svg",
        items: [
          {
            id: "com1",
            title: "Join Challenge",
            icon: "/assets/icons/community.svg",
            tooltip: "Community members join the challenge",
            verticalPosition: 0,
            connectedTo: "do4",
            position: "end",
          },
          {
            id: "com2",
            title: "Ask question",
            icon: "/assets/icons/askquestion.svg",
            tooltip: "Community members can ask questions about the challenge",
            verticalPosition: 1,
            connectedTo: ["com1", "com3"],
            position: "both",
            isVerticalConnection: true,
            verticalConnectionTarget: "com3",
          },
          {
            id: "com3",
            title: "Documentation & forum",
            icon: "/assets/icons/documentationAndForum.svg",
            tooltip:
              "Access documentation and participate in forum discussions",
            verticalPosition: 2,
            connectedTo: ["com2", "dd4", "com4"],
            position: "both",
            isVerticalConnection: true,
            isBidirectional: true,
            verticalConnectionTarget: "com4",
          },
          {
            id: "com4",
            title: "Submit Solutions",
            icon: "/assets/icons/submitRound1Design.svg",
            tooltip: "Community members submit their initial design proposals",
            verticalPosition: 3,
            connectedTo: ["com3", "rev1"],
            position: "both",
            isVerticalConnection: true,
          },
        ],
      },
      {
        id: "review",
        title: "Review Panel",
        icon: "/assets/icons/review.svg",
        items: [
          {
            id: "reviewIdea",
            title: "Review Idea",
            icon: "/assets/icons/reviewRound.svg",
            tooltip: "Panel reviews and evaluates code submissions",
          },
          {
            id: "prepareIdea",
            title: "Prepare Whitepaper",
            icon: "/assets/icons/prepareWhitepaper.svg",
            tooltip: "Prepare whitepaper for the customer",
            verticalPosition: 3,
          },
        ],
      },
    ],
    description:
      "Estée Lauder set out to make beauty more accessible for the 1.3 billion people worldwide living with disabilities. Through Topcoder, they launched an ideation challenge to crowdsource inclusive tech solutions that could transform the beauty experience for everyone. Here's how the Topcoder workflows of project and challenge management led to success:",
  },
};
